- name: Run database container
  docker_container:
    name: my-db
    image: guillaumedmg/tp-devops-postgres:latest
    pull: true
    networks:
      - name: db_network
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "{{ postgres_db }}"
    volumes:
      - tp_db-data:/var/lib/postgresql/data
