- name: Run API container
  docker_container:
    name: backend
    image: guillaumedmg/tp-devops-simple-api:latest
    pull: true
    networks:
      - name: db_network
      - name: proxy_network
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
