name: CD docker

on:
  workflow_run:
    workflows: ["CI backend"]
    branches:
      - main
    types:
      - completed

jobs:
  build-backend-image:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./TD/TP/simpleapi_2
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ github.sha }}

  build-httpd-image:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./TD/TP/http-server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:${{ github.sha }}

  build-database-image:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./TD/TP/postgres
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-postgres:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-postgres:${{ github.sha }}


  deploy:
    needs: [build-backend-image, build-httpd-image, build-database-image]
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml