name: Deploy

on:
  workflow_run:
    workflows: ["CD docker"]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa_takima
          chmod 400 ~/.ssh/id_rsa_takima

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml